"""initial

Revision ID: 8607ade05976
Revises:
Create Date: 2024-05-03 19:03:01.073541

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8607ade05976"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("hashed_password", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_table(
        "salary_statuses",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(), server_default="RUB", nullable=False),
        sa.Column("next_increases_at", sa.DATE(), nullable=False),
        sa.ForeignKeyConstraint(
            ["username"],
            ["users.username"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("salary_statuses")
    op.drop_table("users")
    # ### end Alembic commands ###
